### ISSUE TITLE
SQL database issues when chatting

### ISSUE THREAD

**Issue by ghost** [Lachee/starwatch#1]
I used the Resources/starwatch.sql file to create the basic database, since without the tables being created beforehand the program just spits missing table errors.

![image](https://user-images.githubusercontent.com/51888687/73145793-00621280-4075-11ea-9bed-fafe2ff31ffa.png)

**Comment by ghost** [comment]
This file will fix stuff. Provided from @Lachee 
[koala_4.zip](https://github.com/Lachee/starwatch/files/4115241/koala_4.zip)

**Comment by Lachee** [comment]
Issue Resolved. Updated starwatch.sql was required.
