### ISSUE TITLE
UUIDs not being found

### ISSUE THREAD

**Issue by ghost** [Lachee/starwatch#2]
Exactly as the title suggest, UUIDs are not being parsed properly.

![346](https://user-images.githubusercontent.com/51888687/73146213-1ec90d80-4077-11ea-809e-48c835f03f13.png)
![347](https://user-images.githubusercontent.com/51888687/73146220-2983a280-4077-11ea-9bba-387dbe1d3ba4.png)

**Comment by Lachee** [comment]
UUIDs are only available after a `rcon list` which happens every few minutes. Appropriate events are called to alert the systems the player has been updated.

TL;DR: UUIDs are eventually consistent.
