### ISSUE TITLE
Cannot run UDP checks because the server has disabled its query server.

### ISSUE THREAD

**Issue by ghost** [Lachee/starwatch#3]
Despite the query server being enabled in configuration, SW gives this error message when attempting to connect. Attached is the configuration.

[starbound_server.zip](https://github.com/Lachee/starwatch/files/4115285/starbound_server.zip)

**Comment by Lachee** [comment]
Please check that the `sb_servers` table is configured correctly.

**Comment by ghost** [comment]
![348](https://user-images.githubusercontent.com/51888687/73146535-d9a5db00-4078-11ea-95ac-e26ab317e13b.png)
Figured it'd grab the data from the sb config. What do I do about this?

**Comment by Lachee** [comment]
woops, my bad.
You need to insert a default record. I just remembered the keys are encrypted and there is no easy way to create a new configuration. I will leave this issue open as a TODO for this functionality.

**Comment by Lachee** [comment]
This is fixed in the latest commit.
